import type { Category, KnowledgeCard, FavoriteFolder } from './types'

// 清新统一的卡片背景色
export const CARD_BG_COLOR = 'from-slate-50 to-slate-100 dark:from-slate-800 dark:to-slate-900'

export const getRandomGradient = () => {
  return CARD_BG_COLOR
}

// 专题分类
export const MOCK_CATEGORIES: Category[] = [
  { id: 'funny', name: '搞笑', order: 0 },
  { id: 'history', name: '历史', order: 1 },
  { id: 'military', name: '军事', order: 2 },
  { id: 'science', name: '科学', order: 3 },
  { id: 'philosophy', name: '哲理', order: 4 },
  { id: 'life', name: '生活', order: 5 },
  { id: 'tech', name: '科技', order: 6 },
  { id: 'art', name: '艺术', order: 7 },
  { id: 'sports', name: '体育', order: 8 },
  { id: 'food', name: '美食', order: 9 },
]

// 知识卡片数据 - 每个专栏至少30条
export const MOCK_CARDS: KnowledgeCard[] = [
  // ========== 搞笑 ==========
  { id: 'funny-1', categoryId: 'funny', content: '人生苦短，及时行乐。钱没了可以再赚，头发没了就真没了。', author: '网络热梗', gradient: '', createdAt: '2024-01-01' },
  { id: 'funny-2', categoryId: 'funny', content: '我不是在浪费时间，我是在和时间一起浪。', author: '互联网嘴替', gradient: '', createdAt: '2024-01-02' },
  { id: 'funny-3', categoryId: 'funny', content: '生活不止眼前的苟且，还有读不懂的诗和去不了的远方。', author: '打工人语录', gradient: '', createdAt: '2024-01-03' },
  { id: 'funny-4', categoryId: 'funny', content: '我emo了。不是Eminem的emo，是emotion的emo。', author: '网络热词', gradient: '', createdAt: '2024-01-04' },
  { id: 'funny-5', categoryId: 'funny', content: '成年人的崩溃往往就在一瞬间，但成年人的自愈也是。打开外卖软件的那一刻，又是一条好汉。', author: '干饭人日记', gradient: '', createdAt: '2024-01-05' },
  { id: 'funny-6', categoryId: 'funny', content: '我的钱包就像洋葱，每次打开都让我泪流满面。', author: '月光族', gradient: '', createdAt: '2024-01-06' },
  { id: 'funny-7', categoryId: 'funny', content: '早起的鸟儿有虫吃，早起的虫儿被鸟吃。所以到底要不要早起？', author: '哲学家', gradient: '', createdAt: '2024-01-07' },
  { id: 'funny-8', categoryId: 'funny', content: '我不是懒，我只是进入了节能模式。', author: '环保达人', gradient: '', createdAt: '2024-01-08' },
  { id: 'funny-9', categoryId: 'funny', content: '别人笑我太疯癫，我笑别人看不穿。其实大家都挺傻的。', author: '清醒者', gradient: '', createdAt: '2024-01-09' },
  { id: 'funny-10', categoryId: 'funny', content: '减肥这件事，明天再说吧。反正明天也不会做。', author: '自知之明', gradient: '', createdAt: '2024-01-10' },
  { id: 'funny-11', categoryId: 'funny', content: '熬夜的本质是：白天的自己和晚上的自己在抢夺对身体的控制权。', author: '夜猫子', gradient: '', createdAt: '2024-01-11' },
  { id: 'funny-12', categoryId: 'funny', content: '理想很丰满，现实很骨感，我的钱包更骨感。', author: '打工人', gradient: '', createdAt: '2024-01-12' },
  { id: 'funny-13', categoryId: 'funny', content: '世上无难事，只要肯放弃。', author: '躺平学家', gradient: '', createdAt: '2024-01-13' },
  { id: 'funny-14', categoryId: 'funny', content: '我的优点是：知错能改。我的缺点是：从来不觉得自己错。', author: '自信达人', gradient: '', createdAt: '2024-01-14' },
  { id: 'funny-15', categoryId: 'funny', content: '听说运动可以释放多巴胺，躺着想想运动也可以。', author: '脑内健身', gradient: '', createdAt: '2024-01-15' },
  { id: 'funny-16', categoryId: 'funny', content: '不是我不想社交，是社交不想要我。', author: '社恐患者', gradient: '', createdAt: '2024-01-16' },
  { id: 'funny-17', categoryId: 'funny', content: '我的记忆力很好，好到能记住所有尴尬的事情，然后在深夜反复播放。', author: '失眠症', gradient: '', createdAt: '2024-01-17' },
  { id: 'funny-18', categoryId: 'funny', content: '年轻人要有梦想，万一实现了呢？万一没实现呢？那就继续做梦。', author: '梦想家', gradient: '', createdAt: '2024-01-18' },
  { id: 'funny-19', categoryId: 'funny', content: '我的人生格言是：能躺着绝不坐着，能坐着绝不站着。', author: '躺学专家', gradient: '', createdAt: '2024-01-19' },
  { id: 'funny-20', categoryId: 'funny', content: '别人都是人间清醒，我是人间迷糊。', author: '迷糊蛋', gradient: '', createdAt: '2024-01-20' },
  { id: 'funny-21', categoryId: 'funny', content: '我不是单身狗，我是单身贵族。好吧，我是单身狗。', author: '诚实守信', gradient: '', createdAt: '2024-01-21' },
  { id: 'funny-22', categoryId: 'funny', content: '据说每天喝八杯水可以变漂亮，我喝了八杯奶茶，也没见效果。', author: '奶茶爱好者', gradient: '', createdAt: '2024-01-22' },
  { id: 'funny-23', categoryId: 'funny', content: '工作使我快乐。是工资使我快乐，不是工作。', author: '真相帝', gradient: '', createdAt: '2024-01-23' },
  { id: 'funny-24', categoryId: 'funny', content: '我不是在发呆，我是在思考人生。好吧，我就是在发呆。', author: '思想家', gradient: '', createdAt: '2024-01-24' },
  { id: 'funny-25', categoryId: 'funny', content: '人生建议：少想多睡，少吃多动。我的选择：多想少睡，多吃少动。', author: '反向操作', gradient: '', createdAt: '2024-01-25' },
  { id: 'funny-26', categoryId: 'funny', content: '有些事情不是我不想做，是做了也没用。比如减肥。', author: '减肥失败者', gradient: '', createdAt: '2024-01-26' },
  { id: 'funny-27', categoryId: 'funny', content: '我的运气一直很好，好到足以让我认清现实。', author: '现实主义者', gradient: '', createdAt: '2024-01-27' },
  { id: 'funny-28', categoryId: 'funny', content: '计划赶不上变化，变化赶不上我躺平的速度。', author: '躺平冠军', gradient: '', createdAt: '2024-01-28' },
  { id: 'funny-29', categoryId: 'funny', content: '我有很多优点，最大的优点是脸皮厚。', author: '厚脸皮', gradient: '', createdAt: '2024-01-29' },
  { id: 'funny-30', categoryId: 'funny', content: '人丑就要多读书，我选择继续丑。', author: '颜值担当', gradient: '', createdAt: '2024-01-30' },

  // ========== 历史 ==========
  { id: 'history-1', categoryId: 'history', content: '秦始皇统一六国时只有39岁，而我39岁还在纠结中午吃什么。', author: '历史冷知识', gradient: '', createdAt: '2024-01-01' },
  { id: 'history-2', categoryId: 'history', content: '古罗马人用尿液漱口，因为尿液中的氨有美白牙齿的作用。这个知识我宁愿不知道。', author: '你不知道的历史', gradient: '', createdAt: '2024-01-02' },
  { id: 'history-3', categoryId: 'history', content: '以史为镜，可以知兴替；以人为镜，可以明得失。', author: '唐太宗·李世民', gradient: '', createdAt: '2024-01-03' },
  { id: 'history-4', categoryId: 'history', content: '诸葛亮去世时54岁，周瑜36岁，郭嘉38岁。三国那帮人都年轻得吓人。', author: '三国志', gradient: '', createdAt: '2024-01-04' },
  { id: 'history-5', categoryId: 'history', content: '明朝灭亡时，国库里只剩下不到20万两白银。而一个普通太监的家产，抄出来有100多万两。', author: '明史', gradient: '', createdAt: '2024-01-05' },
  { id: 'history-6', categoryId: 'history', content: '清朝时期，一个四品官员的年俸只有105两银子，还不够在北京买一间厕所。', author: '清史稿', gradient: '', createdAt: '2024-01-06' },
  { id: 'history-7', categoryId: 'history', content: '古埃及人用死老鼠作为止痛药，把它放在嘴里咬着。', author: '古文明奇闻', gradient: '', createdAt: '2024-01-07' },
  { id: 'history-8', categoryId: 'history', content: '唐朝女性的开放程度令人惊讶，骑马、打球、喝酒、穿男装都是常事。', author: '唐朝风俗', gradient: '', createdAt: '2024-01-08' },
  { id: 'history-9', categoryId: 'history', content: '古代皇帝平均寿命只有39岁，当皇帝真的是高危职业。', author: '帝王传', gradient: '', createdAt: '2024-01-09' },
  { id: 'history-10', categoryId: 'history', content: '宋朝的GDP占当时全球的60%，人均收入是当时欧洲的数倍。', author: '经济史', gradient: '', createdAt: '2024-01-10' },
  { id: 'history-11', categoryId: 'history', content: '万里长城的建造耗时2000多年，跨越了多个朝代。', author: '建筑奇迹', gradient: '', createdAt: '2024-01-11' },
  { id: 'history-12', categoryId: 'history', content: '拿破仑身高并不矮，1.69米在当时算正常身高，矮个子的说法是英国人的宣传。', author: '历史误解', gradient: '', createdAt: '2024-01-12' },
  { id: 'history-13', categoryId: 'history', content: '古希腊奥运会运动员全部裸体比赛，而且只允许男性参加和观看。', author: '奥运历史', gradient: '', createdAt: '2024-01-13' },
  { id: 'history-14', categoryId: 'history', content: '维京人非常注重个人卫生，每周至少洗一次澡，在当时的欧洲算很干净了。', author: '北欧历史', gradient: '', createdAt: '2024-01-14' },
  { id: 'history-15', categoryId: 'history', content: '汉武帝刘彻一共有5个皇后，其中3个被废，1个自杀。', author: '汉书', gradient: '', createdAt: '2024-01-15' },
  { id: 'history-16', categoryId: 'history', content: '故宫有9999间半房间，比传说中的10000间少半间，是为了不超过天宫。', author: '建筑传说', gradient: '', createdAt: '2024-01-16' },
  { id: 'history-17', categoryId: 'history', content: '成吉思汗的蒙古帝国版图是历史上最大的连续帝国，横跨欧亚大陆。', author: '蒙古史', gradient: '', createdAt: '2024-01-17' },
  { id: 'history-18', categoryId: 'history', content: '古代的一两银子大约相当于现在的200-300元人民币。', author: '货币史', gradient: '', createdAt: '2024-01-18' },
  { id: 'history-19', categoryId: 'history', content: '曹操一生写了超过100首诗，是三国时期最高产的诗人。', author: '文学史', gradient: '', createdAt: '2024-01-19' },
  { id: 'history-20', categoryId: 'history', content: '秦始皇兵马俑原本是彩色的，颜色随着时间氧化褪色了。', author: '考古发现', gradient: '', createdAt: '2024-01-20' },
  { id: 'history-21', categoryId: 'history', content: '埃及金字塔建造时，猛犸象还没有完全灭绝。', author: '时间线', gradient: '', createdAt: '2024-01-21' },
  { id: 'history-22', categoryId: 'history', content: '哥伦布到死都以为自己发现的是印度，所以把当地人叫做印第安人。', author: '大航海时代', gradient: '', createdAt: '2024-01-22' },
  { id: 'history-23', categoryId: 'history', content: '乾隆皇帝一共写了4万多首诗，比全唐诗的数量还多。但流传下来的名句几乎没有。', author: '文学八卦', gradient: '', createdAt: '2024-01-23' },
  { id: 'history-24', categoryId: 'history', content: '古罗马的消防队其实是私人企业，会先谈好价格才灭火。', author: '罗马史', gradient: '', createdAt: '2024-01-24' },
  { id: 'history-25', categoryId: 'history', content: '牛津大学比阿兹特克帝国还要古老，牛津建校时阿兹特克还不存在。', author: '时间对比', gradient: '', createdAt: '2024-01-25' },
  { id: 'history-26', categoryId: 'history', content: '古代中国人发明了足球，叫蹴鞠，在宋朝达到鼎盛。', author: '体育史', gradient: '', createdAt: '2024-01-26' },
  { id: 'history-27', categoryId: 'history', content: '法老王图坦卡蒙去世时只有19岁，但他的陵墓却是最完整的。', author: '埃及学', gradient: '', createdAt: '2024-01-27' },
  { id: 'history-28', categoryId: 'history', content: '隋朝只存在了38年，但修建的大运河却使用了1400多年。', author: '隋朝工程', gradient: '', createdAt: '2024-01-28' },
  { id: 'history-29', categoryId: 'history', content: '古代的紫色染料比黄金还贵，所以紫色成为了皇室专用色。', author: '色彩历史', gradient: '', createdAt: '2024-01-29' },
  { id: 'history-30', categoryId: 'history', content: '司马迁写《史记》花了14年，被阉割后依然坚持完成，堪称史家绝唱。', author: '史记', gradient: '', createdAt: '2024-01-30' },

  // ========== 军事 ==========
  { id: 'military-1', categoryId: 'military', content: '知己知彼，百战不殆；不知彼而知己，一胜一负；不知彼不知己，每战必殆。', author: '孙子兵法', gradient: '', createdAt: '2024-01-01' },
  { id: 'military-2', categoryId: 'military', content: 'AK-47之所以经典，是因为它简单、可靠、便宜，而且沙子进去了照样能打。', author: '武器百科', gradient: '', createdAt: '2024-01-02' },
  { id: 'military-3', categoryId: 'military', content: '二战时期，美军发现飞机机翼中弹最多，于是加强机翼装甲。统计学家指出：能飞回来的都是机翼中弹的，应该加强其他部位。这就是幸存者偏差。', author: '军事统计学', gradient: '', createdAt: '2024-01-03' },
  { id: 'military-4', categoryId: 'military', content: '善战者无赫赫之功。真正的高手，是让问题消失在萌芽状态。', author: '孙子兵法', gradient: '', createdAt: '2024-01-04' },
  { id: 'military-5', categoryId: 'military', content: '不战而屈人之兵，善之善者也。', author: '孙子兵法', gradient: '', createdAt: '2024-01-05' },
  { id: 'military-6', categoryId: 'military', content: '一颗核弹的威力相当于2万吨TNT炸药，而氢弹的威力是核弹的1000倍。', author: '核武知识', gradient: '', createdAt: '2024-01-06' },
  { id: 'military-7', categoryId: 'military', content: '航空母舰上的跑道只有300米，但战斗机起飞只需要不到100米。', author: '海军装备', gradient: '', createdAt: '2024-01-07' },
  { id: 'military-8', categoryId: 'military', content: '世界上第一辆坦克是英国在一战时发明的，为了保密，伪装成水箱运输，Tank就是水箱的意思。', author: '坦克历史', gradient: '', createdAt: '2024-01-08' },
  { id: 'military-9', categoryId: 'military', content: '狙击手最远击杀记录是3540米，相当于在35个足球场外精确命中目标。', author: '狙击纪录', gradient: '', createdAt: '2024-01-09' },
  { id: 'military-10', categoryId: 'military', content: '美国的B-2隐形轰炸机造价24亿美元一架，比同等重量的黄金还贵。', author: '军费开支', gradient: '', createdAt: '2024-01-10' },
  { id: 'military-11', categoryId: 'military', content: '兵者，诡道也。故能而示之不能，用而示之不用，近而示之远，远而示之近。', author: '孙子兵法', gradient: '', createdAt: '2024-01-11' },
  { id: 'military-12', categoryId: 'military', content: '一艘核潜艇可以在水下连续航行数月不浮出水面，食物比燃料先耗尽。', author: '潜艇知识', gradient: '', createdAt: '2024-01-12' },
  { id: 'military-13', categoryId: 'military', content: '现代战斗机飞行员承受的过载可达9G，相当于体重的9倍压在身上。', author: '飞行员', gradient: '', createdAt: '2024-01-13' },
  { id: 'military-14', categoryId: 'military', content: '攻其无备，出其不意。此兵家之胜，不可先传也。', author: '孙子兵法', gradient: '', createdAt: '2024-01-14' },
  { id: 'military-15', categoryId: 'military', content: '军犬的嗅觉灵敏度是人类的10000倍，可以探测到微量的爆炸物。', author: '军犬训练', gradient: '', createdAt: '2024-01-15' },
  { id: 'military-16', categoryId: 'military', content: '世界上最大的军舰是美国的福特级航母，满载排水量超过10万吨。', author: '海军装备', gradient: '', createdAt: '2024-01-16' },
  { id: 'military-17', categoryId: 'military', content: '夫未战而庙算胜者，得算多也；未战而庙算不胜者，得算少也。', author: '孙子兵法', gradient: '', createdAt: '2024-01-17' },
  { id: 'military-18', categoryId: 'military', content: '特种部队的选拔淘汰率高达90%以上，只有最强者才能通过。', author: '特种训练', gradient: '', createdAt: '2024-01-18' },
  { id: 'military-19', categoryId: 'military', content: '导弹的飞行速度可达音速的20倍以上，从发射到命中只需几分钟。', author: '导弹科技', gradient: '', createdAt: '2024-01-19' },
  { id: 'military-20', categoryId: 'military', content: '上兵伐谋，其次伐交，其次伐兵，其下攻城。', author: '孙子兵法', gradient: '', createdAt: '2024-01-20' },
  { id: 'military-21', categoryId: 'military', content: '现代主战坦克的装甲可以抵御大多数反坦克导弹的正面攻击。', author: '装甲防护', gradient: '', createdAt: '2024-01-21' },
  { id: 'military-22', categoryId: 'military', content: '空降兵从飞机跳下到着陆只有几分钟时间，必须在空中完成所有准备。', author: '空降作战', gradient: '', createdAt: '2024-01-22' },
  { id: 'military-23', categoryId: 'military', content: '兵无常势，水无常形，能因敌变化而取胜者，谓之神。', author: '孙子兵法', gradient: '', createdAt: '2024-01-23' },
  { id: 'military-24', categoryId: 'military', content: '夜视仪可以在完全黑暗的环境下看清数百米外的目标。', author: '夜战装备', gradient: '', createdAt: '2024-01-24' },
  { id: 'military-25', categoryId: 'military', content: '一发巡航导弹的价格可以买一辆豪华跑车，但它只能用一次。', author: '军费对比', gradient: '', createdAt: '2024-01-25' },
  { id: 'military-26', categoryId: 'military', content: '胜兵先胜而后求战，败兵先战而后求胜。', author: '孙子兵法', gradient: '', createdAt: '2024-01-26' },
  { id: 'military-27', categoryId: 'military', content: '军事卫星可以从太空分辨出地面上一个人的脸部特征。', author: '太空侦察', gradient: '', createdAt: '2024-01-27' },
  { id: 'military-28', categoryId: 'military', content: '无人机可以在空中持续飞行超过40小时，是人类飞行员无法达到的。', author: '无人机', gradient: '', createdAt: '2024-01-28' },
  { id: 'military-29', categoryId: 'military', content: '知可以战与不可以战者胜，识众寡之用者胜。', author: '孙子兵法', gradient: '', createdAt: '2024-01-29' },
  { id: 'military-30', categoryId: 'military', content: '电磁轨道炮可以将炮弹加速到7倍音速，比任何传统火炮都快。', author: '未来武器', gradient: '', createdAt: '2024-01-30' },

  // ========== 科学 ==========
  { id: 'science-1', categoryId: 'science', content: '你身体里的每一个原子，都来自于数十亿年前爆炸的恒星。从某种意义上说，我们都是星尘。', author: '卡尔·萨根', gradient: '', createdAt: '2024-01-01' },
  { id: 'science-2', categoryId: 'science', content: '如果把地球历史压缩到24小时，人类在最后1分17秒才出现。我们只是地球的过客。', author: '地球编年史', gradient: '', createdAt: '2024-01-02' },
  { id: 'science-3', categoryId: 'science', content: '章鱼有三颗心脏、蓝色的血液、九个大脑。如果外星人存在，可能就长这样。', author: '海洋生物学', gradient: '', createdAt: '2024-01-03' },
  { id: 'science-4', categoryId: 'science', content: '光速每秒30万公里，看似很快，但宇宙太大了。从地球发出的光，到达最近的恒星需要4年。', author: '天文学常识', gradient: '', createdAt: '2024-01-04' },
  { id: 'science-5', categoryId: 'science', content: '人体有超过7000000000000000000000000000个原子，但它们全部是从死去的恒星中来的。', author: '原子物理', gradient: '', createdAt: '2024-01-05' },
  { id: 'science-6', categoryId: 'science', content: '蜜蜂跳舞是为了告诉同伴食物的位置，它们的舞蹈语言比人类语言更精确。', author: '动物行为学', gradient: '', createdAt: '2024-01-06' },
  { id: 'science-7', categoryId: 'science', content: '闪电的温度是太阳表面温度的5倍，可达30000摄氏度。', author: '气象学', gradient: '', createdAt: '2024-01-07' },
  { id: 'science-8', categoryId: 'science', content: '人的大脑有860亿个神经元，比银河系的恒星数量还多。', author: '神经科学', gradient: '', createdAt: '2024-01-08' },
  { id: 'science-9', categoryId: 'science', content: '水熊虫可以在太空真空中存活，在极端高温和低温中都能生存。', author: '极端生物学', gradient: '', createdAt: '2024-01-09' },
  { id: 'science-10', categoryId: 'science', content: '地球自转正在变慢，恐龙时代的一天只有23小时。', author: '地质学', gradient: '', createdAt: '2024-01-10' },
  { id: 'science-11', categoryId: 'science', content: '蚂蚁的总重量和全人类的总重量差不多，它们真的是地球上最成功的物种之一。', author: '昆虫学', gradient: '', createdAt: '2024-01-11' },
  { id: 'science-12', categoryId: 'science', content: '香蕉是轻度放射性的，因为含有钾-40同位素。但你要吃1000万根才会受到伤害。', author: '核物理', gradient: '', createdAt: '2024-01-12' },
  { id: 'science-13', categoryId: 'science', content: '宇宙中95%的物质是暗物质和暗能量，我们几乎一无所知。', author: '宇宙学', gradient: '', createdAt: '2024-01-13' },
  { id: 'science-14', categoryId: 'science', content: '玻璃其实是一种流动极慢的液体，只是我们人类的寿命不够长，看不到它流动。', author: '材料科学', gradient: '', createdAt: '2024-01-14' },
  { id: 'science-15', categoryId: 'science', content: '人类的DNA有99.9%是相同的，我们之间的差异只有0.1%。', author: '遗传学', gradient: '', createdAt: '2024-01-15' },
  { id: 'science-16', categoryId: 'science', content: '太阳每秒钟损失400万吨质量，但它还能燃烧50亿年。', author: '恒星物理', gradient: '', createdAt: '2024-01-16' },
  { id: 'science-17', categoryId: 'science', content: '海洋中的病毒数量是海洋中所有其他生物总和的15倍。', author: '海洋微生物', gradient: '', createdAt: '2024-01-17' },
  { id: 'science-18', categoryId: 'science', content: '如果你能以光速旅行，从你的视角看，任何距离都是瞬间到达。', author: '相对论', gradient: '', createdAt: '2024-01-18' },
  { id: 'science-19', categoryId: 'science', content: '一茶匙的中子星物质重约60亿吨，比珠穆朗玛峰还重。', author: '天体物理', gradient: '', createdAt: '2024-01-19' },
  { id: 'science-20', categoryId: 'science', content: '植物之间会通过地下真菌网络交流，科学家称之为"森林互联网"。', author: '植物学', gradient: '', createdAt: '2024-01-20' },
  { id: 'science-21', categoryId: 'science', content: '人眼可以分辨约1000万种不同的颜色。', author: '视觉科学', gradient: '', createdAt: '2024-01-21' },
  { id: 'science-22', categoryId: 'science', content: '地球上的所有蚂蚁加起来，大约有20000万亿只。', author: '昆虫统计', gradient: '', createdAt: '2024-01-22' },
  { id: 'science-23', categoryId: 'science', content: '黑洞中心的密度是无限大的，时间在那里停止流动。', author: '相对论', gradient: '', createdAt: '2024-01-23' },
  { id: 'science-24', categoryId: 'science', content: '人类肠道中的细菌数量比人体细胞还多，它们构成了我们的"第二大脑"。', author: '微生物学', gradient: '', createdAt: '2024-01-24' },
  { id: 'science-25', categoryId: 'science', content: '量子纠缠让两个粒子无论相距多远都能瞬间影响对方，爱因斯坦称之为"幽灵般的超距作用"。', author: '量子力学', gradient: '', createdAt: '2024-01-25' },
  { id: 'science-26', categoryId: 'science', content: '地球内核的温度和太阳表面一样热，约6000摄氏度。', author: '地球物理', gradient: '', createdAt: '2024-01-26' },
  { id: 'science-27', categoryId: 'science', content: '如果把人体所有的血管连成一条线，可以绑地球两圈半。', author: '人体解剖', gradient: '', createdAt: '2024-01-27' },
  { id: 'science-28', categoryId: 'science', content: '树懒移动太慢，身上会长出藻类，形成天然的伪装。', author: '动物学', gradient: '', createdAt: '2024-01-28' },
  { id: 'science-29', categoryId: 'science', content: '世界上最深的海沟马里亚纳海沟，如果把珠穆朗玛峰放进去，山顶还在水面下2000米。', author: '海洋地理', gradient: '', createdAt: '2024-01-29' },
  { id: 'science-30', categoryId: 'science', content: '人类已知的宇宙只占整个宇宙的5%，剩下95%是暗物质和暗能量。', author: '宇宙学', gradient: '', createdAt: '2024-01-30' },

  // ========== 哲理 ==========
  { id: 'philosophy-1', categoryId: 'philosophy', content: '人生就像一杯茶，不会苦一辈子，但总会苦一阵子。', author: '人生感悟', gradient: '', createdAt: '2024-01-01' },
  { id: 'philosophy-2', categoryId: 'philosophy', content: '当你凝视深渊时，深渊也在凝视你。', author: '尼采', gradient: '', createdAt: '2024-01-02' },
  { id: 'philosophy-3', categoryId: 'philosophy', content: '未经审视的人生不值得过。但审视太多，人生也过不下去了。', author: '苏格拉底 + 网友补充', gradient: '', createdAt: '2024-01-03' },
  { id: 'philosophy-4', categoryId: 'philosophy', content: '人的一切痛苦，本质上都是对自己无能的愤怒。', author: '王小波', gradient: '', createdAt: '2024-01-04' },
  { id: 'philosophy-5', categoryId: 'philosophy', content: '世界上只有一种真正的英雄主义，那就是认清生活的真相后，依然热爱生活。', author: '罗曼·罗兰', gradient: '', createdAt: '2024-01-05' },
  { id: 'philosophy-6', categoryId: 'philosophy', content: '我思故我在。', author: '笛卡尔', gradient: '', createdAt: '2024-01-06' },
  { id: 'philosophy-7', categoryId: 'philosophy', content: '人生的意义在于追寻意义的过程本身。', author: '维克多·弗兰克尔', gradient: '', createdAt: '2024-01-07' },
  { id: 'philosophy-8', categoryId: 'philosophy', content: '自由不是想做什么就做什么，而是不想做什么就不做什么。', author: '康德', gradient: '', createdAt: '2024-01-08' },
  { id: 'philosophy-9', categoryId: 'philosophy', content: '人不能两次踏进同一条河流。', author: '赫拉克利特', gradient: '', createdAt: '2024-01-09' },
  { id: 'philosophy-10', categoryId: 'philosophy', content: '知道自己无知，是智慧的开始。', author: '苏格拉底', gradient: '', createdAt: '2024-01-10' },
  { id: 'philosophy-11', categoryId: 'philosophy', content: '幸福不是拥有得多，而是计较得少。', author: '人生智慧', gradient: '', createdAt: '2024-01-11' },
  { id: 'philosophy-12', categoryId: 'philosophy', content: '人只有在独处时才能成为自己。', author: '叔本华', gradient: '', createdAt: '2024-01-12' },
  { id: 'philosophy-13', categoryId: 'philosophy', content: '万物皆有裂痕，那是光照进来的地方。', author: '莱昂纳德·科恩', gradient: '', createdAt: '2024-01-13' },
  { id: 'philosophy-14', categoryId: 'philosophy', content: '人生最大的悲剧不是死亡，而是我们在活着时已经内心死去。', author: '马丁·路德·金', gradient: '', createdAt: '2024-01-14' },
  { id: 'philosophy-15', categoryId: 'philosophy', content: '真正的平静，不是避开车马喧嚣，而是在心中修篱种菊。', author: '白落梅', gradient: '', createdAt: '2024-01-15' },
  { id: 'philosophy-16', categoryId: 'philosophy', content: '存在先于本质。', author: '萨特', gradient: '', createdAt: '2024-01-16' },
  { id: 'philosophy-17', categoryId: 'philosophy', content: '人之所以痛苦，在于追求错误的东西。', author: '佛陀', gradient: '', createdAt: '2024-01-17' },
  { id: 'philosophy-18', categoryId: 'philosophy', content: '不要因为走得太远，而忘了为什么出发。', author: '纪伯伦', gradient: '', createdAt: '2024-01-18' },
  { id: 'philosophy-19', categoryId: 'philosophy', content: '你永远不会因为尝试而后悔，只会因为错过而遗憾。', author: '人生哲学', gradient: '', createdAt: '2024-01-19' },
  { id: 'philosophy-20', categoryId: 'philosophy', content: '孤独是一种状态，而寂寞是一种心态。', author: '心理学', gradient: '', createdAt: '2024-01-20' },
  { id: 'philosophy-21', categoryId: 'philosophy', content: '成长就是把哭声调成静音的过程。', author: '成长感悟', gradient: '', createdAt: '2024-01-21' },
  { id: 'philosophy-22', categoryId: 'philosophy', content: '我们都在阴沟里，但总有人仰望星空。', author: '王尔德', gradient: '', createdAt: '2024-01-22' },
  { id: 'philosophy-23', categoryId: 'philosophy', content: '人生没有彩排，每一天都是现场直播。', author: '人生感悟', gradient: '', createdAt: '2024-01-23' },
  { id: 'philosophy-24', categoryId: 'philosophy', content: '最难的不是相守，而是相知。', author: '关系哲学', gradient: '', createdAt: '2024-01-24' },
  { id: 'philosophy-25', categoryId: 'philosophy', content: '人生就像骑自行车，要保持平衡就得不断前进。', author: '爱因斯坦', gradient: '', createdAt: '2024-01-25' },
  { id: 'philosophy-26', categoryId: 'philosophy', content: '与其诅咒黑暗，不如点燃蜡烛。', author: '人生智慧', gradient: '', createdAt: '2024-01-26' },
  { id: 'philosophy-27', categoryId: 'philosophy', content: '时间会告诉你，越是平凡的陪伴，越长久。', author: '时间哲学', gradient: '', createdAt: '2024-01-27' },
  { id: 'philosophy-28', categoryId: 'philosophy', content: '人总是在接近幸福时倍感幸福，在幸福进行时却患得患失。', author: '张爱玲', gradient: '', createdAt: '2024-01-28' },
  { id: 'philosophy-29', categoryId: 'philosophy', content: '别让过去的悲伤，毁掉当下的快乐。', author: '心灵鸡汤', gradient: '', createdAt: '2024-01-29' },
  { id: 'philosophy-30', categoryId: 'philosophy', content: '生命中真正重要的不是你遭遇了什么，而是你如何应对它。', author: '人生哲学', gradient: '', createdAt: '2024-01-30' },

  // ========== 生活 ==========
  { id: 'life-1', categoryId: 'life', content: '成年人最大的自律，就是克制自己去纠正别人的欲望。', author: '社交智慧', gradient: '', createdAt: '2024-01-01' },
  { id: 'life-2', categoryId: 'life', content: '你不必活成别人喜欢的样子，你只需要活成你喜欢的样子。如果别人也喜欢，那是惊喜。', author: '生活态度', gradient: '', createdAt: '2024-01-02' },
  { id: 'life-3', categoryId: 'life', content: '所谓的断舍离，不是扔东西，而是认清什么对你重要，然后把时间和精力花在重要的事情上。', author: '极简生活', gradient: '', createdAt: '2024-01-03' },
  { id: 'life-4', categoryId: 'life', content: '好好睡觉，是最简单也最有效的养生方式。', author: '健康生活', gradient: '', createdAt: '2024-01-04' },
  { id: 'life-5', categoryId: 'life', content: '不要把时间浪费在不值得的人和事上。', author: '时间管理', gradient: '', createdAt: '2024-01-05' },
  { id: 'life-6', categoryId: 'life', content: '学会拒绝，是成年人最重要的能力之一。', author: '社交智慧', gradient: '', createdAt: '2024-01-06' },
  { id: 'life-7', categoryId: 'life', content: '真正的富有，是内心的充实。', author: '生活感悟', gradient: '', createdAt: '2024-01-07' },
  { id: 'life-8', categoryId: 'life', content: '与其抱怨生活的不公，不如努力改变现状。', author: '积极心态', gradient: '', createdAt: '2024-01-08' },
  { id: 'life-9', categoryId: 'life', content: '人生没有白走的路，每一步都算数。', author: '人生感悟', gradient: '', createdAt: '2024-01-09' },
  { id: 'life-10', categoryId: 'life', content: '最好的投资是投资自己。', author: '自我提升', gradient: '', createdAt: '2024-01-10' },
  { id: 'life-11', categoryId: 'life', content: '不要等到失去了才知道珍惜。', author: '人生智慧', gradient: '', createdAt: '2024-01-11' },
  { id: 'life-12', categoryId: 'life', content: '生活不会因为你的焦虑而变好，但会因为你的行动而改变。', author: '行动哲学', gradient: '', createdAt: '2024-01-12' },
  { id: 'life-13', categoryId: 'life', content: '能用钱解决的问题，都不是大问题。', author: '生活智慧', gradient: '', createdAt: '2024-01-13' },
  { id: 'life-14', categoryId: 'life', content: '多读书、多运动、多存钱，这是最简单的自律。', author: '生活建议', gradient: '', createdAt: '2024-01-14' },
  { id: 'life-15', categoryId: 'life', content: '不要把幸福寄托在别人身上。', author: '独立生活', gradient: '', createdAt: '2024-01-15' },
  { id: 'life-16', categoryId: 'life', content: '学会和自己相处，是一生的修行。', author: '心灵成长', gradient: '', createdAt: '2024-01-16' },
  { id: 'life-17', categoryId: 'life', content: '好的关系，是相互成就，而不是相互消耗。', author: '关系智慧', gradient: '', createdAt: '2024-01-17' },
  { id: 'life-18', categoryId: 'life', content: '少说多做，用行动证明自己。', author: '做事原则', gradient: '', createdAt: '2024-01-18' },
  { id: 'life-19', categoryId: 'life', content: '人生最重要的不是所站的位置，而是所朝的方向。', author: '人生方向', gradient: '', createdAt: '2024-01-19' },
  { id: 'life-20', categoryId: 'life', content: '保持好奇心，是保持年轻的秘诀。', author: '心态年轻', gradient: '', createdAt: '2024-01-20' },
  { id: 'life-21', categoryId: 'life', content: '不要在意别人的眼光，做自己就好。', author: '自我认同', gradient: '', createdAt: '2024-01-21' },
  { id: 'life-22', categoryId: 'life', content: '人生苦短，要和让你开心的人在一起。', author: '人际关系', gradient: '', createdAt: '2024-01-22' },
  { id: 'life-23', categoryId: 'life', content: '凡事留余地，日后好相见。', author: '处世之道', gradient: '', createdAt: '2024-01-23' },
  { id: 'life-24', categoryId: 'life', content: '慢一点，生活不是赛跑。', author: '慢生活', gradient: '', createdAt: '2024-01-24' },
  { id: 'life-25', categoryId: 'life', content: '学会感恩，幸福感会翻倍。', author: '感恩心态', gradient: '', createdAt: '2024-01-25' },
  { id: 'life-26', categoryId: 'life', content: '不要和傻瓜争论，他们会把你拉到他们的水平，然后用经验打败你。', author: '社交智慧', gradient: '', createdAt: '2024-01-26' },
  { id: 'life-27', categoryId: 'life', content: '能躺平的人生，是一种福气。', author: '当代生活', gradient: '', createdAt: '2024-01-27' },
  { id: 'life-28', categoryId: 'life', content: '好好吃饭，好好睡觉，好好生活。', author: '简单生活', gradient: '', createdAt: '2024-01-28' },
  { id: 'life-29', categoryId: 'life', content: '每天进步一点点，日积月累就是巨大的改变。', author: '持续成长', gradient: '', createdAt: '2024-01-29' },
  { id: 'life-30', categoryId: 'life', content: '生活的真谛在于简单和真实。', author: '生活哲学', gradient: '', createdAt: '2024-01-30' },

  // ========== 科技 ==========
  { id: 'tech-1', categoryId: 'tech', content: '任何足够先进的科技，都与魔法无异。', author: '亚瑟·克拉克', gradient: '', createdAt: '2024-01-01' },
  { id: 'tech-2', categoryId: 'tech', content: 'Bug不是错误，是未记录的功能。', author: '程序员的自我安慰', gradient: '', createdAt: '2024-01-02' },
  { id: 'tech-3', categoryId: 'tech', content: 'AI不会取代人类，但会用AI的人会取代不会用AI的人。', author: '科技趋势', gradient: '', createdAt: '2024-01-03' },
  { id: 'tech-4', categoryId: 'tech', content: '代码能运行就不要动它。', author: '程序员智慧', gradient: '', createdAt: '2024-01-04' },
  { id: 'tech-5', categoryId: 'tech', content: '在互联网上，没有人知道你是一条狗。', author: '网络匿名性', gradient: '', createdAt: '2024-01-05' },
  { id: 'tech-6', categoryId: 'tech', content: '摩尔定律：每18个月，芯片性能翻一番，价格减一半。', author: '戈登·摩尔', gradient: '', createdAt: '2024-01-06' },
  { id: 'tech-7', categoryId: 'tech', content: '我们高估了技术的短期影响，却低估了它的长期影响。', author: '阿玛拉定律', gradient: '', createdAt: '2024-01-07' },
  { id: 'tech-8', categoryId: 'tech', content: '真正的程序员从不备份，他们只是把代码传到FTP上让全世界共享。', author: '程序员幽默', gradient: '', createdAt: '2024-01-08' },
  { id: 'tech-9', categoryId: 'tech', content: '如果你不能向一个6岁的孩子解释清楚，说明你自己也没理解。', author: '爱因斯坦', gradient: '', createdAt: '2024-01-09' },
  { id: 'tech-10', categoryId: 'tech', content: '最好的代码是没有代码。', author: '简洁原则', gradient: '', createdAt: '2024-01-10' },
  { id: 'tech-11', categoryId: 'tech', content: '数据是新时代的石油。', author: '数据经济', gradient: '', createdAt: '2024-01-11' },
  { id: 'tech-12', categoryId: 'tech', content: '互联网的记忆比金鱼还短，但比大象还长。', author: '网络文化', gradient: '', createdAt: '2024-01-12' },
  { id: 'tech-13', categoryId: 'tech', content: '软件在最后10%的功能上花费90%的开发时间。', author: '软件开发规律', gradient: '', createdAt: '2024-01-13' },
  { id: 'tech-14', categoryId: 'tech', content: '永远不要低估复制粘贴的力量。', author: '程序员生存指南', gradient: '', createdAt: '2024-01-14' },
  { id: 'tech-15', categoryId: 'tech', content: '区块链是信任的机器。', author: '区块链原理', gradient: '', createdAt: '2024-01-15' },
  { id: 'tech-16', categoryId: 'tech', content: '云计算就是别人的电脑。', author: '技术本质', gradient: '', createdAt: '2024-01-16' },
  { id: 'tech-17', categoryId: 'tech', content: '人工智能的目标是让机器像人一样思考，但讽刺的是，我们自己都不知道人类是怎么思考的。', author: 'AI哲学', gradient: '', createdAt: '2024-01-17' },
  { id: 'tech-18', categoryId: 'tech', content: '移动优先，然后是其他一切。', author: '产品设计', gradient: '', createdAt: '2024-01-18' },
  { id: 'tech-19', categoryId: 'tech', content: '注意力是21世纪最稀缺的资源。', author: '数字时代', gradient: '', createdAt: '2024-01-19' },
  { id: 'tech-20', categoryId: 'tech', content: '物联网让一切都能上网，包括你的冰箱和牙刷。', author: 'IoT时代', gradient: '', createdAt: '2024-01-20' },
  { id: 'tech-21', categoryId: 'tech', content: '5G不只是快，而是让万物互联成为可能。', author: '5G技术', gradient: '', createdAt: '2024-01-21' },
  { id: 'tech-22', categoryId: 'tech', content: '元宇宙是互联网的下一个形态，虚实融合的世界。', author: '元宇宙概念', gradient: '', createdAt: '2024-01-22' },
  { id: 'tech-23', categoryId: 'tech', content: '量子计算机能在几秒内完成传统计算机几千年的任务。', author: '量子计算', gradient: '', createdAt: '2024-01-23' },
  { id: 'tech-24', categoryId: 'tech', content: '开源改变世界，协作创造未来。', author: '开源精神', gradient: '', createdAt: '2024-01-24' },
  { id: 'tech-25', categoryId: 'tech', content: '算法决定你看到什么，你以为的选择其实是被选择。', author: '算法伦理', gradient: '', createdAt: '2024-01-25' },
  { id: 'tech-26', categoryId: 'tech', content: '隐私是数字时代最昂贵的奢侈品。', author: '数字隐私', gradient: '', createdAt: '2024-01-26' },
  { id: 'tech-27', categoryId: 'tech', content: '科技是中性的，重要的是使用它的人。', author: '技术伦理', gradient: '', createdAt: '2024-01-27' },
  { id: 'tech-28', categoryId: 'tech', content: '自动驾驶最难的不是技术，而是让人类信任机器。', author: '自动驾驶', gradient: '', createdAt: '2024-01-28' },
  { id: 'tech-29', categoryId: 'tech', content: '电动车不只是换了个引擎，而是重新定义了汽车。', author: '新能源', gradient: '', createdAt: '2024-01-29' },
  { id: 'tech-30', categoryId: 'tech', content: '技术的终极目标是让自己变得透明，用户感受不到它的存在。', author: '产品哲学', gradient: '', createdAt: '2024-01-30' },

  // ========== 艺术 ==========
  { id: 'art-1', categoryId: 'art', content: '艺术的目的不是表现事物的外貌，而是表现其内在意义。', author: '亚里士多德', gradient: '', createdAt: '2024-01-01' },
  { id: 'art-2', categoryId: 'art', content: '每个孩子都是艺术家，问题是如何在长大后保持这种能力。', author: '毕加索', gradient: '', createdAt: '2024-01-02' },
  { id: 'art-3', categoryId: 'art', content: '艺术是谎言，但它教会我们认识真理。', author: '毕加索', gradient: '', createdAt: '2024-01-03' },
  { id: 'art-4', categoryId: 'art', content: '色彩是键盘，眼睛是和弦，灵魂是有无数琴弦的钢琴。', author: '康定斯基', gradient: '', createdAt: '2024-01-04' },
  { id: 'art-5', categoryId: 'art', content: '伟大的艺术家都是模仿者，更伟大的艺术家是偷窃者。', author: '毕加索', gradient: '', createdAt: '2024-01-05' },
  { id: 'art-6', categoryId: 'art', content: '简约是最高级的复杂。', author: '达芬奇', gradient: '', createdAt: '2024-01-06' },
  { id: 'art-7', categoryId: 'art', content: '我用一生的时间才学会像孩子那样画画。', author: '毕加索', gradient: '', createdAt: '2024-01-07' },
  { id: 'art-8', categoryId: 'art', content: '音乐是灵魂的语言。', author: '贝多芬', gradient: '', createdAt: '2024-01-08' },
  { id: 'art-9', categoryId: 'art', content: '建筑是凝固的音乐。', author: '歌德', gradient: '', createdAt: '2024-01-09' },
  { id: 'art-10', categoryId: 'art', content: '摄影的本质是捕捉瞬间的永恒。', author: '亨利·卡蒂埃-布列松', gradient: '', createdAt: '2024-01-10' },
  { id: 'art-11', categoryId: 'art', content: '没有规则的艺术是不存在的，但规则也可以被打破。', author: '艺术原则', gradient: '', createdAt: '2024-01-11' },
  { id: 'art-12', categoryId: 'art', content: '艺术应该让人感到不安，而不是舒适。', author: '当代艺术', gradient: '', createdAt: '2024-01-12' },
  { id: 'art-13', categoryId: 'art', content: '好的设计是尽可能少的设计。', author: '迪特·拉姆斯', gradient: '', createdAt: '2024-01-13' },
  { id: 'art-14', categoryId: 'art', content: '诗是有意义的绘画，绘画是无言的诗。', author: '西蒙尼德斯', gradient: '', createdAt: '2024-01-14' },
  { id: 'art-15', categoryId: 'art', content: '舞蹈是脚的诗歌。', author: '德莱顿', gradient: '', createdAt: '2024-01-15' },
  { id: 'art-16', categoryId: 'art', content: '电影是每秒24帧的谎言。', author: '电影艺术', gradient: '', createdAt: '2024-01-16' },
  { id: 'art-17', categoryId: 'art', content: '艺术家的任务是让平凡变得不平凡。', author: '创作使命', gradient: '', createdAt: '2024-01-17' },
  { id: 'art-18', categoryId: 'art', content: '一幅画的完成不是加法，而是减法。', author: '绘画哲学', gradient: '', createdAt: '2024-01-18' },
  { id: 'art-19', categoryId: 'art', content: '书法是心灵的画像。', author: '书法艺术', gradient: '', createdAt: '2024-01-19' },
  { id: 'art-20', categoryId: 'art', content: '真正的艺术是无法定义的。', author: '艺术本质', gradient: '', createdAt: '2024-01-20' },
  { id: 'art-21', categoryId: 'art', content: '创意是看到别人看不到的东西。', author: '创意思维', gradient: '', createdAt: '2024-01-21' },
  { id: 'art-22', categoryId: 'art', content: '艺术品的价值在于它触动了多少灵魂。', author: '艺术价值', gradient: '', createdAt: '2024-01-22' },
  { id: 'art-23', categoryId: 'art', content: '每一件伟大的艺术品背后都有一个孤独的灵魂。', author: '艺术家', gradient: '', createdAt: '2024-01-23' },
  { id: 'art-24', categoryId: 'art', content: '戏剧是生活的放大镜。', author: '戏剧艺术', gradient: '', createdAt: '2024-01-24' },
  { id: 'art-25', categoryId: 'art', content: '好的艺术让你停下来思考，伟大的艺术改变你的思考方式。', author: '艺术影响', gradient: '', createdAt: '2024-01-25' },
  { id: 'art-26', categoryId: 'art', content: '艺术不是你看到的，而是你让别人看到的。', author: '埃德加·德加', gradient: '', createdAt: '2024-01-26' },
  { id: 'art-27', categoryId: 'art', content: '灵感来自生活，但艺术高于生活。', author: '艺术与生活', gradient: '', createdAt: '2024-01-27' },
  { id: 'art-28', categoryId: 'art', content: '留白是最高级的表达。', author: '东方美学', gradient: '', createdAt: '2024-01-28' },
  { id: 'art-29', categoryId: 'art', content: '艺术的边界就是无边界。', author: '当代艺术', gradient: '', createdAt: '2024-01-29' },
  { id: 'art-30', categoryId: 'art', content: '一千个读者就有一千个哈姆雷特。', author: '艺术解读', gradient: '', createdAt: '2024-01-30' },

  // ========== 体育 ==========
  { id: 'sports-1', categoryId: 'sports', content: '我可以接受失败，但我不能接受不去尝试。', author: '迈克尔·乔丹', gradient: '', createdAt: '2024-01-01' },
  { id: 'sports-2', categoryId: 'sports', content: '天才是1%的灵感加99%的汗水，但那1%的灵感最重要。', author: '爱迪生（原版）', gradient: '', createdAt: '2024-01-02' },
  { id: 'sports-3', categoryId: 'sports', content: '不是每个人都能成为冠军，但每个人都能拥有冠军的心。', author: '体育精神', gradient: '', createdAt: '2024-01-03' },
  { id: 'sports-4', categoryId: 'sports', content: '你不会因为害怕失败而停止尝试。', author: '科比·布莱恩特', gradient: '', createdAt: '2024-01-04' },
  { id: 'sports-5', categoryId: 'sports', content: '重要的不是胜利，而是如何比赛。', author: '奥林匹克精神', gradient: '', createdAt: '2024-01-05' },
  { id: 'sports-6', categoryId: 'sports', content: '没有人能让你感到自卑，除非你同意。', author: '运动心理学', gradient: '', createdAt: '2024-01-06' },
  { id: 'sports-7', categoryId: 'sports', content: '训练时洒的汗水，比赛时少流的泪水。', author: '训练格言', gradient: '', createdAt: '2024-01-07' },
  { id: 'sports-8', categoryId: 'sports', content: '冠军不是在比赛场上诞生的，而是在训练场上铸就的。', author: '穆罕默德·阿里', gradient: '', createdAt: '2024-01-08' },
  { id: 'sports-9', categoryId: 'sports', content: '足球不是生死，足球高于生死。', author: '比尔·香克利', gradient: '', createdAt: '2024-01-09' },
  { id: 'sports-10', categoryId: 'sports', content: '你永远不会独行。', author: '利物浦队歌', gradient: '', createdAt: '2024-01-10' },
  { id: 'sports-11', categoryId: 'sports', content: '真正的对手不是别人，而是昨天的自己。', author: '自我超越', gradient: '', createdAt: '2024-01-11' },
  { id: 'sports-12', categoryId: 'sports', content: '困难只是暂时的，放弃是永久的。', author: '坚持精神', gradient: '', createdAt: '2024-01-12' },
  { id: 'sports-13', categoryId: 'sports', content: '胜利属于最坚忍的人。', author: '拿破仑', gradient: '', createdAt: '2024-01-13' },
  { id: 'sports-14', categoryId: 'sports', content: '篮球是五个人的运动，但冠军需要十二个人。', author: '团队精神', gradient: '', createdAt: '2024-01-14' },
  { id: 'sports-15', categoryId: 'sports', content: '我见过凌晨四点的洛杉矶。', author: '科比·布莱恩特', gradient: '', createdAt: '2024-01-15' },
  { id: 'sports-16', categoryId: 'sports', content: '痛苦是短暂的，荣耀是永恒的。', author: '马拉松精神', gradient: '', createdAt: '2024-01-16' },
  { id: 'sports-17', categoryId: 'sports', content: '努力不一定成功，但放弃一定失败。', author: '运动员信条', gradient: '', createdAt: '2024-01-17' },
  { id: 'sports-18', categoryId: 'sports', content: '记录就是用来打破的。', author: '竞技精神', gradient: '', createdAt: '2024-01-18' },
  { id: 'sports-19', categoryId: 'sports', content: '更快、更高、更强。', author: '奥林匹克格言', gradient: '', createdAt: '2024-01-19' },
  { id: 'sports-20', categoryId: 'sports', content: '不在沉默中爆发，就在沉默中灭亡。', author: '竞技心态', gradient: '', createdAt: '2024-01-20' },
  { id: 'sports-21', categoryId: 'sports', content: '汗水不会背叛你。', author: '训练信念', gradient: '', createdAt: '2024-01-21' },
  { id: 'sports-22', categoryId: 'sports', content: '最后的冲刺决定一切。', author: '比赛关键', gradient: '', createdAt: '2024-01-22' },
  { id: 'sports-23', categoryId: 'sports', content: '跌倒了爬起来，这就是运动员的本能。', author: '永不放弃', gradient: '', createdAt: '2024-01-23' },
  { id: 'sports-24', categoryId: 'sports', content: '体育教会我们如何优雅地失败。', author: '体育教育', gradient: '', createdAt: '2024-01-24' },
  { id: 'sports-25', categoryId: 'sports', content: '没有什么能阻挡一颗想要赢的心。', author: '必胜信念', gradient: '', createdAt: '2024-01-25' },
  { id: 'sports-26', categoryId: 'sports', content: '球场上没有永远的王者。', author: '竞技真理', gradient: '', createdAt: '2024-01-26' },
  { id: 'sports-27', categoryId: 'sports', content: '细节决定成败，态度决定高度。', author: '竞技态度', gradient: '', createdAt: '2024-01-27' },
  { id: 'sports-28', categoryId: 'sports', content: '身体可以疲惫，意志不能垮塌。', author: '耐力精神', gradient: '', createdAt: '2024-01-28' },
  { id: 'sports-29', categoryId: 'sports', content: '对手越强，胜利越甜。', author: '挑战精神', gradient: '', createdAt: '2024-01-29' },
  { id: 'sports-30', categoryId: 'sports', content: '运动让人年轻，坚持让人不凡。', author: '运动价值', gradient: '', createdAt: '2024-01-30' },

  // ========== 美食 ==========
  { id: 'food-1', categoryId: 'food', content: '没有什么事是一顿火锅解决不了的，如果有，那就两顿。', author: '干饭人', gradient: '', createdAt: '2024-01-01' },
  { id: 'food-2', categoryId: 'food', content: '人生苦短，甜点要先吃。卡路里不重要，快乐最重要。', author: '美食家', gradient: '', createdAt: '2024-01-02' },
  { id: 'food-3', categoryId: 'food', content: '世界上唯一不能辜负的，就是美食和爱。', author: '人生哲学', gradient: '', createdAt: '2024-01-03' },
  { id: 'food-4', categoryId: 'food', content: '治愈不开心最好的办法就是吃，如果吃不好，那就吃两顿。', author: '干饭哲学', gradient: '', createdAt: '2024-01-04' },
  { id: 'food-5', categoryId: 'food', content: '吃饱了才有力气减肥。', author: '减肥悖论', gradient: '', createdAt: '2024-01-05' },
  { id: 'food-6', categoryId: 'food', content: '唯有美食与爱不可辜负。', author: '美食名言', gradient: '', createdAt: '2024-01-06' },
  { id: 'food-7', categoryId: 'food', content: '深夜的泡面，是灵魂的慰藉。', author: '夜宵党', gradient: '', createdAt: '2024-01-07' },
  { id: 'food-8', categoryId: 'food', content: '人是铁饭是钢，一顿不吃饿得慌。', author: '民间智慧', gradient: '', createdAt: '2024-01-08' },
  { id: 'food-9', categoryId: 'food', content: '好的厨师知道，最好的调味料是饥饿。', author: '烹饪哲学', gradient: '', createdAt: '2024-01-09' },
  { id: 'food-10', categoryId: 'food', content: '奶茶是当代年轻人的续命水。', author: '奶茶文化', gradient: '', createdAt: '2024-01-10' },
  { id: 'food-11', categoryId: 'food', content: '每一道菜都是一个故事。', author: '美食文化', gradient: '', createdAt: '2024-01-11' },
  { id: 'food-12', categoryId: 'food', content: '民以食为天，我以零食为命。', author: '零食爱好者', gradient: '', createdAt: '2024-01-12' },
  { id: 'food-13', categoryId: 'food', content: '最好的餐厅是妈妈的厨房。', author: '家的味道', gradient: '', createdAt: '2024-01-13' },
  { id: 'food-14', categoryId: 'food', content: '吃货的人生格言：吃饱再说。', author: '吃货宣言', gradient: '', createdAt: '2024-01-14' },
  { id: 'food-15', categoryId: 'food', content: '烧烤和啤酒是夏天的标配。', author: '夏日美食', gradient: '', createdAt: '2024-01-15' },
  { id: 'food-16', categoryId: 'food', content: '饺子就酒，越喝越有。', author: '饮食传统', gradient: '', createdAt: '2024-01-16' },
  { id: 'food-17', categoryId: 'food', content: '早餐要吃好，午餐要吃饱，晚餐要吃少。但我全部都要吃好吃饱。', author: '真实想法', gradient: '', createdAt: '2024-01-17' },
  { id: 'food-18', categoryId: 'food', content: '一个人吃饭叫觅食，两个人吃饭才叫约会。', author: '美食社交', gradient: '', createdAt: '2024-01-18' },
  { id: 'food-19', categoryId: 'food', content: '食物是最好的旅行纪念品。', author: '美食旅行', gradient: '', createdAt: '2024-01-19' },
  { id: 'food-20', categoryId: 'food', content: '小时候的味道，一辈子都忘不掉。', author: '味觉记忆', gradient: '', createdAt: '2024-01-20' },
  { id: 'food-21', categoryId: 'food', content: '最香的饭是别人碗里的。', author: '人性洞察', gradient: '', createdAt: '2024-01-21' },
  { id: 'food-22', categoryId: 'food', content: '辣椒是快乐的源泉。', author: '嗜辣一族', gradient: '', createdAt: '2024-01-22' },
  { id: 'food-23', categoryId: 'food', content: '咖啡是打工人的氧气。', author: '打工人日常', gradient: '', createdAt: '2024-01-23' },
  { id: 'food-24', categoryId: 'food', content: '减肥从明天开始，今天先吃点好的。', author: '永恒的明天', gradient: '', createdAt: '2024-01-24' },
  { id: 'food-25', categoryId: 'food', content: '炸鸡配可乐，快乐没烦恼。', author: '快乐搭配', gradient: '', createdAt: '2024-01-25' },
  { id: 'food-26', categoryId: 'food', content: '美食是世界上最好的语言。', author: '美食无国界', gradient: '', createdAt: '2024-01-26' },
  { id: 'food-27', categoryId: 'food', content: '冬天的第一杯热奶茶，比夏天的第一支雪糕还治愈。', author: '季节美食', gradient: '', createdAt: '2024-01-27' },
  { id: 'food-28', categoryId: 'food', content: '吃是为了活着，但活着不仅仅是为了吃。不对，有时候就是为了吃。', author: '吃货哲学', gradient: '', createdAt: '2024-01-28' },
  { id: 'food-29', categoryId: 'food', content: '最治愈的事情就是：吃顿好的。', author: '治愈系', gradient: '', createdAt: '2024-01-29' },
  { id: 'food-30', categoryId: 'food', content: '人生得意须尽欢，胡吃海喝需趁早。', author: '美食人生', gradient: '', createdAt: '2024-01-30' },
]

// 默认收藏夹
export const DEFAULT_FAVORITE_FOLDER: FavoriteFolder = {
  id: 'default',
  name: '我的收藏',
  color: '#f43f5e',
  cardIds: [],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}
